name: Github Action Demo
on: 
  push:
    branches:
      - main
    paths-ignore: 
      - .github/**
  
  pull_request:
    branches: 
      - main
  
  schedule:
    - cron: 15 6 * * 0
  
  workflow_dispatch:
  
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Output the name of the event that triggered the workflow
        shell: |
          echo "The job was triggered by event: ${{ github.event_name }}"
          echo "Ref ${{ github.ref }}"
      
      - name: checkout repo
        uses: actions/checkout@v3.0.2
  
        
